### ISSUE TITLE
App Not Installed

### ISSUE THREAD

**Issue by kr-nahid** [yuzumone/Recordachi#11]
#### Expected behavior
it should be in install smoothly like all other apps .

#### Actual behavior
when i click for install app not installed .

#### How to reproduce
* download the app from [here](https://github.com/yuzumone/Recordachi/releases)
* click install when download the apk
* and note the bug

> Browser/App version: Recordachi v1.0.1
 Operating system: **Symphony v75** android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=rMqKN7iNFpA

**Comment by yuzumone** [comment]
I released a new version v1.0.2. Can not install this?
